# SITE SETTINGS
title: GloBAM
author: GloBAM partners

# SOCIAL PROFILES
social:
  email: globam@vogelwarte.ch
  twitter: globam_net
  github: enram

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.0
posts_on_home: 3
tweets_on_home: true
archive_permalink: /news/
github_edit: true
logo: /assets/images/globam-nav-logo.png
colors:
  links: "#93c243"
  banner: "#93c243"
  footer: "#513266"

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"
